-- Crée la table 'messages'
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  read boolean default false
);

-- Sécurité (RLS)
alter table messages enable row level security;

-- Tout le monde peut écrire (envoyer un message)
create policy "Enable insert for all users"
on messages for insert
with check (true);

-- Seul l'admin peut lire/modifier/supprimer
create policy "Enable all access for authenticated users only"
on messages for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');
