-- Crée la table 'articles'
create table articles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  category text,
  excerpt text,
  content text,
  image text,
  cta text,
  date text
);

-- Active la sécurité (RLS) mais permet à tout le monde de lire/écrire pour simplifier (à modifier plus tard pour sécuriser)
alter table articles enable row level security;

create policy "Enable read access for all users"
on articles for select
using (true);

create policy "Enable insert access for all users"
on articles for insert
with check (true);
