-- Crée la table 'products'
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  price text,
  description text,
  features text[], -- Tableau de chaînes de caractères
  stripeUrl text
);

-- Sécurité (RLS)
alter table products enable row level security;

create policy "Enable read access for all users"
on products for select
using (true);

create policy "Enable insert access for all users"
on products for insert
with check (true);

create policy "Enable delete access for all users"
on products for delete
using (true);
