-- Auto-generated script to perfectly rebalance Encyclopedia Volumes

UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '99';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '100';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '101';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '102';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '103';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '104';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '105';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '106';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '107';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '108';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '109';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '110';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '111';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '112';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '113';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '114';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '115';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '116';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '117';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '118';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '119';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '120';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '121';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '122';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '123';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '124';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '125';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '126';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '127';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '14';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '26';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '128';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '129';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '130';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '131';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '132';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '133';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '134';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '135';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '136';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '137';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '138';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '139';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '140';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '141';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '142';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '143';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '144';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '145';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '146';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '147';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '148';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '149';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '150';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '151';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '152';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '153';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '154';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '155';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '156';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '157';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '158';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '159';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '160';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '161';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '162';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '163';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '164';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '165';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '166';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '167';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '168';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '169';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '170';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '171';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '172';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '173';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '174';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '175';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '176';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '28';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '177';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '178';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '179';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '180';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '181';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '182';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '183';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '184';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '185';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '186';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '187';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '188';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '25';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '189';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '190';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '191';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '192';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '193';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '194';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '195';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '196';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '197';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '198';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '199';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '200';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '201';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '202';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '203';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '29';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '30';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '204';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '205';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '206';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '207';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '208';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '27';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '16';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '21';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '62';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '63';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '64';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '280';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '32';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '33';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '65';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '35';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '36';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '38';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '66';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '40';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '55';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '67';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '68';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '48';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '69';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '50';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '70';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '52';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '53';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '54';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '71';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '72';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '73';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '74';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '75';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '76';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '77';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '78';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '79';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '80';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '81';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '82';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '83';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '84';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '56';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '85';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '58';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '59';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '22';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '23';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '24';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '15';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '17';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '57';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '86';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '31';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '34';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '37';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '39';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '49';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '51';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '87';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '88';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '89';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '90';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '91';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '92';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '93';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '94';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '95';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '96';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '97';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '98';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '209';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '210';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '211';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '212';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '213';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '214';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '215';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '216';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '217';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '218';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '219';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '220';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '221';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '222';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '223';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '224';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '225';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '226';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '227';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '228';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '229';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '230';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '231';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '232';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '233';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '234';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '235';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '236';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '237';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '238';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '239';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '240';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '241';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '242';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '243';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '244';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '245';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '246';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '247';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '248';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '249';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '250';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '251';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '252';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '253';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '254';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '255';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '256';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '257';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '258';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '259';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '260';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '261';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '262';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '263';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '264';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '265';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '266';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '267';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '268';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '269';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '270';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '271';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '272';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '273';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '274';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '275';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '276';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '277';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '278';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '279';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '281';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '282';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '283';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '284';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '285';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '286';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '287';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '288';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '289';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '290';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '291';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '292';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '293';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '294';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '295';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '296';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '297';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '298';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '299';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '300';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '301';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '302';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '303';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '304';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '305';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '306';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '307';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '308';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '309';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '310';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '311';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '312';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '374';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '313';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '314';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '315';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '316';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '317';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '318';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '319';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '320';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '321';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '322';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '323';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '324';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '325';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '326';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '327';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '328';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '329';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '330';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '331';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '332';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '333';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '334';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '335';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '336';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '337';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '338';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '339';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '340';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '341';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '342';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '343';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '344';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '345';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '346';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '347';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '348';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '349';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '350';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '351';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '352';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '353';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '354';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '355';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '356';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '357';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '358';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '359';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '360';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '361';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '362';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '363';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '364';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '365';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '366';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '367';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '368';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '369';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '370';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '371';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '372';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '373';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '375';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '376';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '377';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '378';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '379';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '380';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '381';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '382';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '383';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '384';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '385';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '386';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '387';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '388';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '389';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '390';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '391';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '392';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '393';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '394';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '395';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '396';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '397';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '398';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '399';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '400';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '401';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '402';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '403';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '404';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '405';
UPDATE articles SET category = 'Volume 3 : La Science de la Santé' WHERE id = '406';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '407';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '409';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '411';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '412';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '414';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '415';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '417';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '418';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '420';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '421';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '423';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '424';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '428';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '429';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '431';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '432';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '434';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '435';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '437';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '438';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '440';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '441';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '443';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '444';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '446';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '447';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '449';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '450';
UPDATE articles SET category = 'Volume 1 : La Science de la Force' WHERE id = '452';
UPDATE articles SET category = 'Volume 2 : La Science de l''Endurance' WHERE id = '453';
